apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  containers:
        - name: my-image
          image: kartikay1181/my-image:latest
          ports:
            - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd